version: "3.9"

services:
  postgres:
    container_name: mts-tth-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "mts-postgresql"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
