version: "3"

services:
  bank:
    container_name: bank
    image: bank
    restart: always
    env_file:
      - .env
    ports:
      - "30002:30002"

  postgres:
    container_name: mts-tth-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "mts-postgresql"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
